;zend_extension=xdebug

xdebug.mode=debug
xdebug.client_port=9003
xdebug.client_host=host.docker.internal

; Вариант 1 (просто): всегда дебажит запрос
xdebug.start_with_request=yes

; Вариант 2 (рекомендую, быстрее): дебаг только по триггеру
;xdebug.start_with_request=trigger
xdebug.trigger_value=1

xdebug.log_level=0
; xdebug.log=/tmp/xdebug.log
